import {
	navegacion,
	galery,
	generalidades,
	generalidadesInfo,
	input,
	select,
	phones,
	footerNavegacion,
	redes,
	card,
	btnApadrina,
	teest,
	preguntas,
	galeria,
	cardBlog,
	eventsFuturos,
	eventspasados,
} from "./js/data";

const handlerBarsContext = {
	"/index.html": {
		title: "Inicio",
		logo: "https://acoes.org/wp-content/uploads/2023/10/LG-FUNDACION-BN-2-2.png",
		navegacion: navegacion,
		galery: galery,
		generalidades: generalidades,
		generalidadesInfo: generalidadesInfo,
		input: input,
		select: select,
		phones: phones,
		footerNavegacion: footerNavegacion,
		redes: redes,
	},
	"/page/donaciones.html": {
		title: "Donaciones",
		logo: "https://acoes.org/wp-content/uploads/2023/10/LG-FUNDACION-BN-2-2.png",
		navegacion: navegacion,
		btnApadrina: btnApadrina,
		card: card,
		phones: phones,
		footerNavegacion: footerNavegacion,
		redes: redes,
	},
	"/page/programas.html": {
		title: "Programas",
		logo: "https://acoes.org/wp-content/uploads/2023/10/LG-FUNDACION-BN-2-2.png",
		navegacion: navegacion,
		galery: galery,
		input: input,
		phones: phones,
		footerNavegacion: footerNavegacion,
		teest: teest,
		redes: redes,
	},
	"/page/pfrecuentes.html": {
		title: "Frecuentes",
		logo: "https://acoes.org/wp-content/uploads/2023/10/LG-FUNDACION-BN-2-2.png",
		navegacion: navegacion,
		galery: galery,
		input: input,
		phones: phones,
		footerNavegacion: footerNavegacion,
		teest: teest,
		preguntas: preguntas,
		redes: redes,
	},
	"/page/comoayudar.html": {
		title: "Como Ayudar",
		logo: "https://acoes.org/wp-content/uploads/2023/10/LG-FUNDACION-BN-2-2.png",
		navegacion: navegacion,
		galery: galery,
		input: input,
		phones: phones,
		footerNavegacion: footerNavegacion,
	},
	"/page/galeria.html": {
		title: "Galeria",
		logo: "https://acoes.org/wp-content/uploads/2023/10/LG-FUNDACION-BN-2-2.png",
		navegacion: navegacion,
		galery: galery,
		phones: phones,
		footerNavegacion: footerNavegacion,
		galeria: galeria,
		redes: redes,
	},
	"/page/blog.html": {
		title: "Blog",
		logo: "https://acoes.org/wp-content/uploads/2023/10/LG-FUNDACION-BN-2-2.png",
		navegacion: navegacion,
		card: card,
		phones: phones,
		footerNavegacion: footerNavegacion,
		redes: redes,
		cardBlog: cardBlog,
	},
	"/page/eventos.html": {
		title: "Eventos",
		logo: "https://acoes.org/wp-content/uploads/2023/10/LG-FUNDACION-BN-2-2.png",
		navegacion: navegacion,
		phones: phones,
		footerNavegacion: footerNavegacion,
		redes: redes,
		eventspasados: eventspasados,
		eventsFuturos: eventsFuturos,
	},
};

const pageContext = (page) => {
	const context = { ...handlerBarsContext[page] };
	return context;
};
export default pageContext;
